### PR TITLE
Added support for this.locals

### PR DESCRIPTION
**Pull request by Siedrix**
The content of this.locals is not been passed to the template, now it is.

### CODE REVIEW

**Comment by coderhaoxin** [comment]
why not use `state`? 

```
The recommended namespace for passing information through middleware and to your frontend views
```

**Comment by Siedrix** [comment]
I was following this example for csrf tokens, `this.state` seems to work, but `this.locals` didnt so i sended the fix. 

https://www.npmjs.com/package/koa-locals#example

What is the use for locals? Is it global values?

**Comment by coderhaoxin** [comment]
https://github.com/koa-modules/koa-locals has beed deprecated

**Comment by coderhaoxin** [comment]
https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxstate

`state` is recommended.

**Comment by Siedrix** [comment]
Ok, in that case, close this pull request, its not needed

**Pull request closed without merging**
